name: My Workflow

on: push

jobs:
  checkout:
    name: 레포지토리 확인
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [a1-2, e2-1]
    steps:
        - uses: actions/checkout@master

  kill:
    name: 스크린 닫기
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [a1-2, e2-1]
    steps:
      - run: screen -X -S bot quit
        
  run:
    name: 프로세스 실행
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [a1-2, e2-1]
    steps:
      - run: screen -dmS bot sh -c "npm ci; npm run dev"