name: My Workflow

on: push

jobs:
  pull:
    name: 깃풀이다이자식아
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [a1-2, e2-1]
    defaults:
      run:
        working-directory: /home/ubuntu/EKEBot-Discord
    steps:
      - name: git pull
        run: git pull
      - name: run
        run: |
          chmod 777 run.sh
          ./run.sh