name: My Workflow

on: push

jobs:
  pull:
    name: 깃풀이다이자식아
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [a1-2, e2-1]
    defaults:
      run:
        working-directory: /home/ubuntu/EKEBot-Discord
    steps:
      - name: git pull
        run: git pull
      - name: check session
        run: |
          session=bot
          tmux has-session -t $session || tmux new-session -d -s $session
      - name: run
        run: |
          tmux send-keys -t $session C-c
          tmux send-keys -t $session "bash" C-m
          tmux send-keys -t $session "npm run start" C-m